//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentaBancariaMultiUsuario._4.Infrastructure_Data.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Datetime { get; set; }
        public int BankAccountId { get; set; }
    
        public virtual BankAccounts BankAccounts { get; set; }
    }
}
