// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkSQLApi.Models;

public partial class Workers
{
    [Key]
    public int Id { get; set; }

    public int IdUser { get; set; }

    public int YearsOfExperience { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("Workers")]
    public virtual Users IdUserNavigation { get; set; }
}