// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkSQLApi.Models;

[Index("IdUser", Name = "IX_Workers", IsUnique = true)]
public partial class Workers
{
    [Key]
    public int Id { get; set; }

    public int IdUser { get; set; }

    public int YearsOfExperience { get; set; }

    [Column(TypeName = "date")]
    public DateTime? LeavingDate { get; set; }

    [ForeignKey("IdUser")]
    [InverseProperty("Workers")]
    public virtual Users IdUserNavigation { get; set; }
}