// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EntityFrameworkSQLApi.Models;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkSQLApi.DbContextFolder;

public partial class TestSQLServerConnectionFromNet6Context : DbContext
{
    public TestSQLServerConnectionFromNet6Context(DbContextOptions<TestSQLServerConnectionFromNet6Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Workers> Workers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Workers>(entity =>
        {
            entity.HasOne(d => d.IdUserNavigation).WithOne(p => p.Workers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Workers_Users1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}